### ISSUE TITLE
Passera purged from FDROID?

### ISSUE THREAD

**Issue by ksuhiyp** [mwgg/passera#13]
I no more see passera app in the FDROID what happened?

**Comment by mwgg** [comment]
Hi! Thanks for letting me know! This must be something related to their recent infrastructure changes. I've opened up an issue with them, since Passera is included and should be still available in their repo.

**Comment by soaringowl2145** [comment]
Is there any update on this?

**Comment by mwgg** [comment]
It turned out to be a problem on the F-Droid that affected several apps and it should be resolved soon. Relevant F-Droid issue: https://gitlab.com/fdroid/fdroiddata/issues/788

**Comment by soaringowl2145** [comment]
Thanks!

**Comment by ksuhiyp** [comment]
still missing

**Comment by soaringowl2145** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/788

**Comment by soaringowl2145** [comment]
The issue relating to passera is still open but it is back in the repo now.
