### ISSUE TITLE
Compatibility with Palemoon

### ISSUE THREAD

**Issue by ultrazauber** [mwgg/passera#6]
Hello dear sir or madam,
thank your for reading in advance.

Although Palemoon is a browser which is on par with FF or Waterfox, I think, I sadly can not use your wonderful addon on it. Due to the thing, that it isn't available for "FF 24.9".
Sadly Palemoon has this Version number and sends it somehow; I am not sure whether Palemoon should fix this for better compatibility or you could add sum' exception to your addon to let it work with Palemoon and maybe other forks of FF, which work with diff. version numbers but same functionality... if it is in your interest and/or are in the mood for it.
Thanks again.

Regards,
uz~

**Comment by mwgg** [comment]
Hi,

Unfortunately, the addon would not work with anything based on FF 29 or earlier. It is possible to rewrite the addon using the classic SDK but I'm not sure if I will ever get to that.
